/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/trees.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/trees.glb')
  return (
    <group {...props} dispose={null} >
      <mesh name="imagetostl_mesh0" geometry={nodes.imagetostl_mesh0.geometry} material={materials.mat0} />
    </group>
  )
}

useGLTF.preload('/trees.glb')
