'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 ./public/models/Cargo.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Avatar(props : any) {
  const { nodes, materials } : any = useGLTF('/models/Cargo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.container_Cube011.geometry} material={materials.Container} />
      <mesh geometry={nodes.door_2_Cube018.geometry} material={materials.Container} />
      <mesh geometry={nodes.door_1_Cube019.geometry} material={materials.Container} />
      <mesh geometry={nodes.locking_bar_1_Cylinder016_1.geometry} material={materials.Locking_bar} />
      <mesh geometry={nodes.locking_bar_1_Cylinder016_2.geometry} material={materials.Container} />
      <mesh geometry={nodes.locking_bar_2_Cylinder010_1.geometry} material={materials.Locking_bar} />
      <mesh geometry={nodes.locking_bar_2_Cylinder010_2.geometry} material={materials.Container} />
    </group>
  )
}

useGLTF.preload('/models/Cargo.glb')
