'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/tree.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/models/tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.imagetostl_mesh0.geometry} material={materials.mat0} />
    </group>
  )
}

useGLTF.preload('/models/tree.glb')
