/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/butterfly.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Butterfly(props) {
  const { nodes, materials } = useGLTF('/models/butterfly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Sphere44" geometry={nodes.Sphere44.geometry} material={materials['3iLleather White']} position={[-4.386, 5.377, 2.558]} rotation={[-0.67, -0.822, -0.42]} scale={0.846} />
      <mesh name="Line10" geometry={nodes.Line10.geometry} material={materials['3iLleather White']} position={[-4.744, 6.801, 6.135]} rotation={[-1.924, 0.282, 2.275]} scale={[-0.846, 0.846, 0.846]} />
      <mesh name="Sphere45" geometry={nodes.Sphere45.geometry} material={materials['3iLleather White']} position={[-3.54, 5.506, 3.616]} rotation={[-0.67, -0.822, -0.42]} scale={0.846} />
      <mesh name="Line12" geometry={nodes.Line12.geometry} material={materials.goldd} position={[-3.51, 5.071, 3.059]} rotation={[1.217, -0.282, 0.867]} scale={0.895} />
      <mesh name="Sphere46" geometry={nodes.Sphere46.geometry} material={materials['3iLleather White']} position={[-5.732, 7.939, 8.392]} rotation={[-0.15, -1.074, 3.119]} scale={[-0.348, 0.348, 0.799]} />
      <mesh name="Sphere47" geometry={nodes.Sphere47.geometry} material={materials['3iLleather White']} position={[-9.795, 7.317, 3.313]} rotation={[-0.14, -0.725, 3.127]} scale={[0.348, 0.348, 0.799]} />
      <mesh name="Line13" geometry={nodes.Line13.geometry} material={materials['3iLleather White']} position={[-7.253, 6.417, 2.997]} rotation={[-1.924, 0.282, 2.275]} scale={0.846} />
      <mesh name="Box06" geometry={nodes.Box06.geometry} material={materials['01- ']} position={[6.922, 14.459, 2.575]} rotation={[-0.665, -0.845, 0.281]} scale={0.846} />
      <mesh name="Line15" geometry={nodes.Line15.geometry} material={materials['01- ']} position={[5.732, 12.423, 6.197]} rotation={[0.694, 0.185, 0.865]} scale={[1.406, 1.406, 1.36]} />
      <mesh name="Line14" geometry={nodes.Line14.geometry} material={materials['01- ']} position={[8.924, 6.173, 0.296]} rotation={[0.694, 0.185, 0.865]} scale={[1.406, 1.406, 1.36]} />
      <mesh name="Line17" geometry={nodes.Line17.geometry} material={materials['07 - Default7']} position={[1.116, 2.975, 0.008]} rotation={[1.217, -0.282, 0.867]} scale={0.846} />
    </group>
  )
}

useGLTF.preload('/models/butterfly.glb')
