'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/trees.glb 
*/
// hovering effect : https://discourse.threejs.org/t/on-hover-of-a-3d-model-highlight/50171

import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'

export function Treess(props : any) {
  const { nodes, materials } :any = useGLTF('/models/trees.glb')
  const [shiny, setShiny] = useState(false)
  return (
    <group {...props} rotation={[1.6,0,0]} position={[5,-2,-1]} dispose={null}>
      <mesh geometry={nodes.imagetostl_mesh0.geometry} 
      material={materials.mat0}
      material-color={shiny ? "#F29422" : "#3C8C30"} 
      onPointerEnter={() => setShiny(true)}
      onPointerLeave={() => setShiny(false)}
       />
    </group>
  )
}

useGLTF.preload('/models/trees.glb')
