'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx

*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TwoTree(props) {
  const { nodes, materials } = useGLTF('/models/TwoTree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group834066651.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group476324890.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1456453523.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group910432207.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group699188109.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1701856745.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group2134159723.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group23053643.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1190759120.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1763764806.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group68856542.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1454638135.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1417025955.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1417025955_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1129352399.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1129352399_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1365140907.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1365140907_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh664234440.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh664234440_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1435870510.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1435870510_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1358194235.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1358194235_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1669679150.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1669679150_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1919417890.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1919417890_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1599212695.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1599212695_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh2053801240.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh2053801240_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh2007776685.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh2007776685_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh2132753463.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh2132753463_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh615833065.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh615833065_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh498467273.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh498467273_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh860548694.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh860548694_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1165148268.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1165148268_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh199553800.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh199553800_1.geometry} material={materials.mat13} />
    </group>
  )
}

useGLTF.preload('/models/TwoTree.glb')
